package com.github.fhermansson.gradle.assertj.plugin

import org.assertj.core.api.Assertions.assertThat
import org.gradle.testkit.runner.GradleRunner
import org.gradle.testkit.runner.TaskOutcome
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File

class GenerateAssertionsFunctionalTest {
    @TempDir
    lateinit var projectDir: File

    private fun writeProject(
        buildScript: String,
        kotlinDsl: Boolean = false,
    ) {
        if (kotlinDsl) {
            projectDir.resolve("settings.gradle.kts").writeText("rootProject.name = \"sample\"\n")
        } else {
            projectDir.resolve("settings.gradle").writeText("rootProject.name = 'sample'\n")
        }
        projectDir
            .resolve(
                if (kotlinDsl) "build.gradle.kts" else "build.gradle",
            ).writeText(buildScript)
        projectDir.resolve("src/main/java/com/example/model/Item.java").apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.example.model;

                public class Item {
                    private String name;
                    public String getName() { return name; }
                    public void setName(String name) { this.name = name; }
                }
                """.trimIndent(),
            )
        }
    }

    @Test
    fun `generateAssertions produces assertion class and entry point and compiles into tests`() {
        writeProject(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
            }

            repositories { mavenCentral() }
            dependencies {
                testImplementation 'org.assertj:assertj-core:3.27.7'
                // Generated sources carry @jakarta.annotation.Generated by default
                testCompileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'
            }
            """.trimIndent(),
        )

        val build =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("compileTestJava", "--warning-mode=all")
                .build()

        assertThat(build.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        assertThat(build.task(":compileTestJava")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)

        val generatedDir = projectDir.resolve("build/generated/sources/assertj/test")
        val assertionClass = generatedDir.resolve("com/example/model/Assertions.java")
        val entryPoint = generatedDir.resolve("com/example/model/ItemAssert.java")
        assertThat(assertionClass).describedAs("Assertions entry point not generated").exists()
        assertThat(entryPoint).describedAs("ItemAssert not generated").exists()
        assertThat(entryPoint.readText()).contains("class ItemAssert")
    }

    @Test
    fun `custom GenerateAssertions task inherits extension defaults`() {
        writeProject(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
                entryPointPackage = 'com.example.assertj'
            }

            repositories { mavenCentral() }
            dependencies { testImplementation 'org.assertj:assertj-core:3.27.7' }

            import com.github.fhermansson.gradle.assertj.plugin.GenerateAssertions

            tasks.register('generateOtherAssertions', GenerateAssertions) {
                classOrPackageNames = ['com.example.model']
                outputDir = layout.buildDirectory.dir('other-generated-java')
                testSourceSet = sourceSets.test
            }
            """.trimIndent(),
        )

        val build =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("generateOtherAssertions", "--warning-mode=all")
                .build()

        assertThat(build.task(":generateOtherAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        val outDir = projectDir.resolve("build/other-generated-java")
        assertThat(outDir.resolve("com/example/model/ItemAssert.java")).exists()
        assertThat(outDir.resolve("com/example/assertj/Assertions.java")).exists()
    }

    @Test
    fun `build is configuration cache compatible`() {
        writeProject(
            """
            plugins {
                java
                id("com.github.fhermansson.assertj-generator")
            }

            assertjGenerator {
                classOrPackageNames = listOf("com.example.model")
            }

            repositories { mavenCentral() }
            dependencies { testImplementation("org.assertj:assertj-core:3.27.7") }
            """.trimIndent(),
            kotlinDsl = true,
        )

        /*
         * First run stores the configuration; second run must reuse it (UP-TO-DATE task
         * outcomes prove the cached configuration was used, not rebuilt).
         */
        GradleRunner
            .create()
            .withProjectDir(projectDir)
            .withPluginClasspath()
            .withArguments("generateAssertions", "--configuration-cache", "--warning-mode=all")
            .build()
        val reuse =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("generateAssertions", "--configuration-cache", "--warning-mode=all")
                .build()

        assertThat(reuse.output).contains("Reusing configuration cache.")
        assertThat(reuse.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.UP_TO_DATE)
    }

    @Test
    fun `generateAssertions is build-cacheable`() {
        writeProject(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
            }

            repositories { mavenCentral() }
            """.trimIndent(),
        )

        GradleRunner
            .create()
            .withProjectDir(projectDir)
            .withPluginClasspath()
            .withArguments("generateAssertions", "--build-cache")
            .build()
        /*
         * Removing the outputs and rebuilding must not re-run the generator:
         * the cache entry is restored instead (FROM-CACHE).
         */
        projectDir.resolve("build/generated").deleteRecursively()
        val fromCache =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("generateAssertions", "--build-cache")
                .build()

        assertThat(fromCache.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.FROM_CACHE)
        val generatedDir = projectDir.resolve("build/generated/sources/assertj/test")
        assertThat(generatedDir.resolve("com/example/model/ItemAssert.java")).exists()
    }

    @Test
    fun `generated assertions are usable in a consumer unit test`() {
        writeProject(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
            }

            repositories { mavenCentral() }
            dependencies {
                testImplementation 'org.assertj:assertj-core:3.27.7'
                testImplementation 'org.junit.jupiter:junit-jupiter:5.14.4'
                testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
                // Generated sources carry @jakarta.annotation.Generated by default
                testCompileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'
            }

            tasks.withType(Test).configureEach { useJUnitPlatform() }
            """.trimIndent(),
        )
        projectDir.resolve("src/test/java/com/example/ItemTest.java").apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.example;

                import com.example.model.Item;
                import org.junit.jupiter.api.Test;

                import static com.example.model.Assertions.assertThat;

                class ItemTest {
                    @Test
                    void generatedAssertionVerifiesProperty() {
                        Item item = new Item();
                        item.setName("abc");
                        assertThat(item).hasName("abc");
                    }
                }
                """.trimIndent(),
            )
        }

        val test =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("test", "--warning-mode=all")
                .build()

        assertThat(test.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        assertThat(test.task(":compileTestJava")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        assertThat(test.task(":test")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)

        val generated =
            projectDir
                .resolve("build/generated/sources/assertj/test/com/example/model/ItemAssert.java")
                .readText()
        assertThat(generated).contains("@jakarta.annotation.Generated")
    }

    @Test
    fun `generated assertions work in a consumer test running JUnit 6`() {
        /*
         * Combination guard: the generated assertions are plain Java classes and must
         * stay usable with the current JUnit major, not just the 5.x line the other
         * fixtures use.
         */
        writeProject(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
            }

            repositories { mavenCentral() }
            dependencies {
                testImplementation 'org.assertj:assertj-core:3.27.7'
                testImplementation 'org.junit.jupiter:junit-jupiter:6.1.3'
                testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
                // Generated sources carry @jakarta.annotation.Generated by default
                testCompileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'
            }

            java {
                // JUnit 6 requires Java 17+
                toolchain { languageVersion = JavaLanguageVersion.of(21) }
            }

            tasks.withType(Test).configureEach { useJUnitPlatform() }
            """.trimIndent(),
        )
        projectDir.resolve("src/test/java/com/example/ItemTest.java").apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.example;

                import com.example.model.Item;
                import org.junit.jupiter.api.Test;

                import static com.example.model.Assertions.assertThat;

                class ItemTest {
                    @Test
                    void generatedAssertionVerifiesProperty() {
                        Item item = new Item();
                        item.setName("abc");
                        assertThat(item).hasName("abc");
                    }
                }
                """.trimIndent(),
            )
        }

        val test =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("test", "--warning-mode=all")
                .build()

        assertThat(test.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        assertThat(test.task(":test")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
    }

    @Test
    fun `generateForNonPublicFields includes non-public field assertions`() {
        fun buildScript(allFields: Boolean) =
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
                generateForNonPublicFields = $allFields
            }

            repositories { mavenCentral() }
            """.trimIndent()

        writeProject(buildScript(allFields = false))
        projectDir.resolve("src/main/java/com/example/model/Plain.java").apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.example.model;

                public class Plain {
                    String hidden; // package-private field, no accessor
                }
                """.trimIndent(),
            )
        }

        fun run() = GradleRunner
            .create()
            .withProjectDir(projectDir)
            .withPluginClasspath()
            .withArguments("generateAssertions", "--rerun-tasks")
            .build()

        // Default: fields without public accessors get no assertions.
        run()
        val defaultGenerated =
            projectDir
                .resolve("build/generated/sources/assertj/test/com/example/model/PlainAssert.java")
                .readText()
        assertThat(defaultGenerated).doesNotContain("hasHidden")

        // With generateForNonPublicFields: the package-private field is asserted too.
        writeProject(buildScript(allFields = true))
        val build = run()

        assertThat(build.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        val generated =
            projectDir
                .resolve("build/generated/sources/assertj/test/com/example/model/PlainAssert.java")
                .readText()
        assertThat(generated).contains("hasHidden")
    }

    @Test
    fun `excludes set on the extension filters generated assertions`() {
        /*
         * Regression guard: extension-level excludes must reach the task (the 2.0.0
         * rewrite initially missed the wiring, silently ignoring the option).
         */
        writeProject(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
                excludes = ['.*Item']
            }

            repositories { mavenCentral() }
            """.trimIndent(),
        )

        val build =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("generateAssertions")
                .build()

        assertThat(build.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        val generatedDir = projectDir.resolve("build/generated/sources/assertj/test")
        assertThat(generatedDir.resolve("com/example/model/ItemAssert.java")).doesNotExist()
    }

    @Test
    fun `entryPointTypes BDD generates BDDAssertions entry point`() {
        writeProject(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            import org.assertj.assertions.generator.AssertionsEntryPointType

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
                entryPointTypes = [AssertionsEntryPointType.BDD]
            }

            repositories { mavenCentral() }
            """.trimIndent(),
        )

        val build =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("generateAssertions")
                .build()

        assertThat(build.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        val generatedDir = projectDir.resolve("build/generated/sources/assertj/test")
        assertThat(generatedDir.resolve("com/example/model/BDDAssertions.java")).exists()
        assertThat(generatedDir.resolve("com/example/model/Assertions.java")).doesNotExist()
    }

    @Test
    fun `entryPointInherits false generates standalone entry point`() {
        /*
         * entryPointInherits=true (default) makes the entry point extend
         * org.assertj.core.api.Assertions; with false, the class must be standalone.
         */
        fun buildScript(inherits: Boolean) =
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
                entryPointInherits = $inherits
            }

            repositories { mavenCentral() }
            """.trimIndent()

        fun run() = GradleRunner
            .create()
            .withProjectDir(projectDir)
            .withPluginClasspath()
            .withArguments("generateAssertions", "--rerun-tasks")
            .build()

        fun entryPoint() = projectDir
            .resolve("build/generated/sources/assertj/test/com/example/model/Assertions.java")
            .readText()

        writeProject(buildScript(inherits = true))
        run()
        assertThat(entryPoint()).contains("extends org.assertj.core.api.Assertions")

        writeProject(buildScript(inherits = false))
        run()
        assertThat(entryPoint()).doesNotContain("extends org.assertj.core.api.Assertions")
    }

    @Test
    fun `cleanOutputDir false keeps stale files and true removes them`() {
        fun buildScript(clean: Boolean) =
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
                cleanOutputDir = $clean
            }

            repositories { mavenCentral() }
            """.trimIndent()

        val staleFile =
            projectDir.resolve("build/generated/sources/assertj/test/com/example/model/Stale.java")

        fun run() = GradleRunner
            .create()
            .withProjectDir(projectDir)
            .withPluginClasspath()
            .withArguments("generateAssertions", "--rerun-tasks")
            .build()

        writeProject(buildScript(clean = false))
        run()
        staleFile.parentFile.mkdirs()
        staleFile.writeText("// stale")
        run()
        assertThat(staleFile).exists()

        writeProject(buildScript(clean = true))
        run()
        assertThat(staleFile).doesNotExist()
    }

    @Test
    fun `sourceSet can point at a non-main source set`() {
        /*
         * Assertions must be generated from the classes of the configured source
         * set, not just main.
         */
        projectDir.resolve("settings.gradle").writeText("rootProject.name = 'sample'\n")
        projectDir.resolve("build.gradle").writeText(
            """
            plugins {
                id 'java'
                id 'com.github.fhermansson.assertj-generator'
            }

            sourceSets {
                extra {
                    java {
                        srcDir 'src/extra/java'
                    }
                }
            }

            assertjGenerator {
                sourceSet = sourceSets.extra
                classOrPackageNames = ['com.example.extra']
            }

            repositories { mavenCentral() }
            """.trimIndent(),
        )
        projectDir.resolve("src/extra/java/com/example/extra/Widget.java").apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.example.extra;

                public class Widget {
                    public String getLabel() { return "label"; }
                }
                """.trimIndent(),
            )
        }

        val build =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("generateAssertions")
                .build()

        assertThat(build.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        assertThat(
            projectDir.resolve("build/generated/sources/assertj/test/com/example/extra/WidgetAssert.java"),
        ).exists()
    }

    @Test
    fun `assertions are generated for kotlin classes and usable in kotlin tests`() {
        /*
         * Kotlin main sources, Kotlin test sources: the whole chain must work —
         * generation reads compiled Kotlin classes from the runtime classpath, and the
         * generated Java sources must join the Kotlin test compile.
         */
        projectDir.resolve("settings.gradle").writeText("rootProject.name = 'sample'\n")
        projectDir.resolve("build.gradle").writeText(
            """
            plugins {
                id 'org.jetbrains.kotlin.jvm' version '2.0.21'
                id 'com.github.fhermansson.assertj-generator'
            }

            repositories { mavenCentral() }
            dependencies {
                testImplementation 'org.assertj:assertj-core:3.27.7'
                testImplementation 'org.junit.jupiter:junit-jupiter:5.14.4'
                testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
                testCompileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'
            }

            tasks.withType(Test).configureEach { useJUnitPlatform() }

            assertjGenerator {
                classOrPackageNames = ['com.example.model']
            }
            """.trimIndent(),
        )
        projectDir.resolve("src/main/kotlin/com/example/model/KotlinItem.kt").apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.example.model

                data class KotlinItem(val name: String)

                enum class KotlinStatus { ACTIVE, INACTIVE }
                """.trimIndent(),
            )
        }
        projectDir.resolve("src/test/kotlin/com/example/KotlinItemTest.kt").apply {
            parentFile.mkdirs()
            writeText(
                """
                package com.example

                import com.example.model.KotlinItem
                import com.example.model.KotlinStatus
                import org.junit.jupiter.api.Test
                import org.assertj.core.api.Assertions.assertThatThrownBy
                import com.example.model.Assertions.assertThat

                class KotlinItemTest {
                    @Test
                    fun generatedAssertionVerifiesKotlinProperty() {
                        val item = KotlinItem("abc")
                        assertThat(item).hasName("abc")
                        assertThat(item.name).isEqualTo("abc")
                    }

                    @Test
                    fun kotlinEnumAssertionWorks() {
                        /*
                         * Kotlin enums compiled with 1.9+ carry a kotlin.enums.EnumEntries
                         * internal EnumEntries field; class inspection must resolve it through the
                         * task's isolated class loader (regression guard).
                         */
                        assertThat(KotlinStatus.ACTIVE).isEqualTo(KotlinStatus.ACTIVE)
                    }

                    @Test
                    fun generatedAssertionFailsWithDescriptiveMessage() {
                        val item = KotlinItem("abc")
                        assertThatThrownBy { assertThat(item).hasName("foo") }
                            .isInstanceOf(AssertionError::class.java)
                            .hasMessageContaining("Expecting name of")
                            .hasMessageContaining("to be:")
                            .hasMessageContaining("<foo>")
                            .hasMessageContaining("but was:")
                            .hasMessageContaining("<abc>")
                    }
                }
                """.trimIndent(),
            )
        }

        val test =
            GradleRunner
                .create()
                .withProjectDir(projectDir)
                .withPluginClasspath()
                .withArguments("test", "--warning-mode=all")
                .build()

        assertThat(test.task(":generateAssertions")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        assertThat(test.task(":compileTestKotlin")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
        assertThat(test.task(":test")!!.outcome).isEqualTo(TaskOutcome.SUCCESS)
    }
}
